services:
  mysql:
    image: 'mysql:8.0'
    container_name: 'mysql_supermercado'
    environment:
      - 'MYSQL_DATABASE=db_supermercado'
      - 'MYSQL_USER=${DATABASE_USERNAME}'
      - 'MYSQL_PASSWORD=${DATABASE_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=root'
    ports:
      - '3306:3306'